#!/bin/sh

APPDIR=$(readlink -f "$0")
APPDIR=$(dirname "$APPDIR")
java -Djna.nosys=true -Djava.library.path="$APPDIR:$APPDIR/lib" -cp "$APPDIR:$APPDIR/lib/visualController.jar:$APPDIR/lib/core.jar:$APPDIR/lib/jogl-all.jar:$APPDIR/lib/gluegen-rt.jar:$APPDIR/lib/jogl-all-natives-linux-i586.jar:$APPDIR/lib/gluegen-rt-natives-linux-i586.jar:$APPDIR/lib/peasy-math.jar:$APPDIR/lib/peasycam.jar:$APPDIR/lib/artnet4j.jar:$APPDIR/lib/controlP5.jar:$APPDIR/lib/jsyn-20171016.jar:$APPDIR/lib/javamp3-1.0.3.jar:$APPDIR/lib/sound.jar:$APPDIR/lib/gstreamer-java.jar:$APPDIR/lib/jna.jar:$APPDIR/lib/video.jar:$APPDIR/lib/udp.jar" visualController "$@"
